# pytest.ini
[pytest]
python_files = *_tests.py test_*.py  # Это мы добавили в предыдущем шаге
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*            # Устанавливает правила для имен функций

markers =
    registration: marker for tests related to user registration process
    regression: marker for tests related to user regression process
    authorization: marker for tests related to user authorization process
    courses: marker for tests related to user courses process